services:
    web:
        container_name: tv_web
        restart: unless-stopped
        image: veneridze/laravel-octane:8.4
        command: '/usr/bin/php84 /app/tv/artisan octane:start --server=roadrunner --rpc-port=6001 --host=0.0.0.0 --port=80 --workers=20'
        healthcheck:
            test: ["CMD-SHELL", "/usr/bin/php84 /app/tv/artisan octane:status --no-ansi | grep -q 'Octane server is running' && exit 0 || exit 1"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
        environment:
            LARAVEL_SAIL: 1
        volumes:
            - '.:/app/tv'
        networks:
            - database
            - web
            # - search
    # queue:
    #     container_name: tv_queue
    #     image: veneridze/laravel-octane:8.4
    #     # network_mode: "service:web"
    #     command: ["/bin/bash", "-c", "cd /app/tv && /usr/bin/php84 -d variables_order=EGPCS artisan queue:work"]
    #     environment:
    #         LARAVEL_SAIL: 1
    #     depends_on:
    #         - web
    #     volumes:
    #         - '.:/app/tv'
    #     networks:
    #         - database
    #         - search
    # schedule:
    #     container_name: tv_schedule
    #     restart: unless-stopped
    #     image: veneridze/laravel-octane:8.4
    #     # network_mode: "service:web"
    #     command: ["/bin/bash", "-c", "cd /app/tv && /usr/bin/php84 -d variables_order=EGPCS artisan schedule:work"]
    #     environment:
    #         LARAVEL_SAIL: 1
    #     depends_on:
    #         - web
    #     volumes:
    #         - '.:/app/tv'
    #     networks:
    #         - database
    #         - search
networks:
    web:
        external: true  # Используем существующую сеть
    database:
        external: true  # Используем существующую сеть
    # search:
    #     external: true  # Используем существующую сеть